name: myenv
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - ca-certificates
  - libffi
  - ncurses
  - openssl
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - flask
  - pip:
      - absl-py
      - aiobotocore
      - aiohttp
      - aiohttp-retry
      - aioitertools
      - aiosignal
      - alembic
      - amqp
      - aniso8601
      - annotated-types
      - antlr4-python3-runtime
      - anyio
      - appdirs
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - asttokens
      - astunparse
      - async-lru
      - async-timeout
      - asyncssh
      - atpublic
      - attrs
      - babel
      - backcall
      - backports-zoneinfo
      - beautifulsoup4
      - billiard
      - bleach
      - blinker
      - boto3
      - botocore
      - cachetools
      - celery
      - certifi
      - cffi
      - charset-normalizer
      - click
      - click-didyoumean
      - click-plugins
      - click-repl
      - cloudpickle
      - colorama
      - comm
      - configobj
      - contourpy
      - cryptography
      - cycler
      - debugpy
      - decorator
      - defusedxml
      - deprecated
      - dictdiffer
      - diskcache
      - distro
      - docker
      - dpath
      - dulwich
      - dvc
      - dvc-data
      - dvc-http
      - dvc-objects
      - dvc-render
      - dvc-s3
      - dvc-studio-client
      - dvc-task
      - entrypoints
      - exceptiongroup
      - executing
      - fastjsonschema
      - filelock
      - flask
      - flatbuffers
      - flatten-dict
      - flufl-lock
      - fonttools
      - fqdn
      - frozenlist
      - fsspec
      - funcy
      - gast
      - gitdb
      - zipp
      - gitpython
      - google-auth
      - google-auth-oauthlib
      - google-pasta
      - grandalf
      - graphene
      - graphql-core
      - graphql-relay
      - greenlet
      - grpcio
      - gto
      - gunicorn
      - h11
      - h5py
      - httpcore
      - httpx
      - hydra-core
      - idna
      - importlib-metadata
      - importlib-resources
      - iniconfig
      - ipykernel
      - ipython
      - isoduration
      - iterative-telemetry
      - itsdangerous
      - jedi
      - jinja2
      - jmespath
      - joblib
      - json5
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - jupyter-client
      - jupyter-core
      - jupyter-events
      - jupyter-lsp
      - jupyter-server
      - jupyter-server-terminals
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-server
      - keras
      - kiwisolver
      - kombu
      - libclang
      - mako
      - markdown
      - markdown-it-py
      - markupsafe
      - matplotlib
      - matplotlib-inline
      - mdurl
      - mistune
      - mlflow
      - multidict
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - networkx
      - notebook-shim
      - numpy
      - oauthlib
      - omegaconf
      - opentelemetry-api
      - opentelemetry-sdk
      - opentelemetry-semantic-conventions
      - opt-einsum
      - orjson
      - overrides
      - packaging
      - pandas
      - pandocfilters
      - parso
      - pathspec
      - pexpect
      - pickleshare
      - pillow
      - pkgutil-resolve-name
      - platformdirs
      - pluggy
      - prometheus-client
      - prompt-toolkit
      - protobuf
      - psutil
      - ptyprocess
      - pure-eval
      - pyarrow
      - pyasn1
      - pyasn1-modules
      - pycparser
      - pydantic
      - pydantic-core
      - pydot
      - pygit2
      - pygments
      - pygtrie
      - pyparsing
      - pytest
      - python-dateutil
      - python-json-logger
      - pytz
      - pyyaml
      - pyzmq
      - querystring-parser
      - referencing
      - requests
      - requests-oauthlib
      - rfc3339-validator
      - rfc3986-validator
      - rich
      - rpds-py
      - rsa
      - ruamel-yaml
      - ruamel-yaml-clib
      - s3fs
      - s3transfer
      - scikit-learn
      - scipy
      - scmrepo
      - semver
      - send2trash
      - shellingham
      - shortuuid
      - shtab
      - six
      - smmap
      - sniffio
      - soupsieve
      - sqlalchemy
      - sqlparse
      - sqltrie
      - stack-data
      - tabulate
      - tensorboard
      - tensorboard-data-server
      - tensorflow
      - tensorflow-estimator
      - tensorflow-io-gcs-filesystem
      - termcolor
      - terminado
      - threadpoolctl
      - tinycss2
      - tomli
      - tomlkit
      - tornado
      - tqdm
      - traitlets
      - typer
      - types-python-dateutil
      - typing-extensions
      - tzdata
      - uri-template
      - urllib3
      - vine
      - voluptuous
      - wcwidth
      - webcolors
      - webencodings
      - websocket-client
      - werkzeug
      - wrapt
      - yarl
      - zc-lockfile
      - virtualenv
