name: Auto Merge Development to Main

on:
  push:
    branches:
      - development

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Configure Git
        run: |
          git config --global user.email "jyothikrishnan.vilangara@gmail.com"
          git config --global user.name "jyothikrishn"

      - name: Merge development branch to main
        run: |
          git fetch origin
          git checkout main
          git merge --no-ff origin/development -m "Merging changes from development to main"
          git push origin main